arb-dir: lib/src/l10n
template-arb-file: localization_en.arb
output-localization-file: component_localizations.dart
output-class: ComponentLocalizations
synthetic-package: false
nullable-getter: false
